#echo new yaml
woversion: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

